name: Publish Package to npmjs
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@dc323e67f16fb5f7663d20ff7941f27f5809e9b6 # v2
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@1f8c6b94b26d0feae1e387ca63ccbdc44d27b561 # v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - run: yarn install --frozen-lockfile
      - run: yarn version --new-version ${{ github.event.release.tag_name }} --no-git-tag-version
      - run: yarn publish --non-interactive && clean-package restore
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}