name: Publish Package to npmjs
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write 
      contents: read
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
        with:
          node-version: '24.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npm version ${{ github.event.release.tag_name }} --no-git-tag-version
      - run: npm publish --provenance && npx clean-package restore
        env:
          NODE_AUTH_TOKEN: ''
