name: Test
on:
  push:
  pull_request:
env:
  FORCE_COLOR: 2
jobs:
  full:
    name: Node.js 20 Full
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
      - name: Install Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: 20
      - name: Install dependencies
        uses: bahmutov/npm-install@v1
      - name: Run tests
        run: yarn test
  short:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 22
          - 18
    name: Node.js ${{ matrix.node-version }} Quick
    steps:
      - name: Checkout the repository
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        uses: bahmutov/npm-install@v1
      - name: Run unit tests
        run: npx jest
